[project]
name = "langchain-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shreyagautam1526", email = "shreyagautam1526@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.15.0",
    "google-genai>=2.22.0",
    "huggingface-hub>=1.30.0",
    "langchain>=1.4.0",
    "langchain-classic>=1.0.8",
    "langchain-core>=1.6.2",
    "langchain-google-genai>=4.4.0",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.0",
    "numpy>=2.5.3",
    "openai>=3.8.0",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.63.0",
    "torch>=2.14.0",
    "transformers>=5.16.1",
]

[project.scripts]
langchain-models = "langchain_models:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
